# This is a development compose file.
version: "3.3"
services:
  event-application-service:
    container_name: docker_event_application_service
    build: 
      context: services/event-application-service
    volumes:
      - ~/.config/:/root/.config
    environment:
      - APP_NAME=lohfinder-app
  api_service:
    build: ./services/api_service
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/api_service:/usr/src/api_service/
    ports:
      - 8000:8000
    env_file:
      - ./services/api_service/.env.dev
  user_service:
    build: ./services/user_service
    command: python3 main.py
  event_service:
    container_name: event_service
    build:
      context: ./
      dockerfile: ./services/eventservice/Dockerfile
    volumes:
      - '~/servicedata:/data/eventservice/db'
  user_app_service:
    container_name: user_app_service
    build:
      context: ./
      dockerfile: ./services/userappservice/Dockerfile
    volumes:
      - '~/servicedata:/data/uappservice/db'

